### ISSUE TITLE
入门任务十五——企业站+sass简介

### ISSUE THREAD

**Issue by wddsyc** [wddsyc/alltask#15]
# sass
Sass(Syntactically Awesome Style Sheets) 是一个 CSS 的扩展，它通过提供一些 CSS 不具备的特性，如嵌套，循环，函数等，使样式文件更加模块化和易于维护，并最终编译回 CSS 文件用于部署。
PS:sass只是css。
# 安装及使用
npm 安装 node-sass
`npm install -g node-sass`
使用
`node-sass -wro css scss`
# 变量
sass变量用于储存一些常用颜色，数值。
- 声明变量并使用
```sass
$color-primary: #0070e9;

a {
  color: $color-primary;
}

.btn-primary {
  background-color: $color-primary;
}
```
## 在选择器内定义全局变量
```scss
.content {
$width: 100px !global;
}
```
# 嵌套
- 选择器嵌套
```sass
.header {
  height: 60px;
  .navbar {
    display: flex;
    > li {
      flex: 1;
      a {
        dislay: block;
        font-size: 18px;
      }
    }
  }
}
```
- 属性嵌套
```scss
.fancy {
  font: {
    size: 12rem;
    weight: bold;
    family: fantasy;
  }
}
```
# &引用
`&`用于引用父选择器
```sass
a {
  color: #555;
  &:hover {
    color: #333;
  }
  &:active {
    color: #444;
  }
}
```
# @import
![image](https://user-images.githubusercontent.com/29122433/33161196-cd2d3a78-d05c-11e7-9817-55f645d33087.png)
- _a.scss文件
![image](https://user-images.githubusercontent.com/29122433/33161202-d3f8e4ba-d05c-11e7-8a49-04051dc20359.png)
- _b.scss文件
![image](https://user-images.githubusercontent.com/29122433/33161215-e3fb01d6-d05c-11e7-82d1-228f354b0f99.png)
- e.scss文件，将两者导入
![image](https://user-images.githubusercontent.com/29122433/33161220-ed335032-d05c-11e7-9658-32f5ecb748bd.png)
- e.css文件生成

## 嵌套@import
Sass 的 `@import` 指令可以嵌套在选择器内，产生嵌套效果。
```sass
.container {
@import "content";
}
```
# 注释
- 单行注释`//`会在scss转成css后移除
- 多行注释`/*  */ `则可以保留

# 混入Mixin
## @mixin定义，@include导入
`scss`
```scss
@mixin text-truncate() {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.text {
 max-width: 800px;
  @include text-truncate();
}
```
`css`
```css
.text-ellipsis {
  max-width: 800px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
## 加入参数
`scss`
```scss
@mixin border-right-radius($radius) {
  border-top-right-radius: $radius;
  border-bottom-right-radius: $radius;
}

.sidebar {
  @include border-right-radius(4px);
}
```
`css`
```css
.sidebar {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px;
}
```
# 扩展 Extend

Sass 提供了 `@extend` 用于扩展类和其他选择器。`@extend` 工作原理是生成形如 `A, B` 的选择器。

## @extend

`SCSS`
```sass
.btn {
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  display: inline-block;
}

.btn-primary {
  @extend .btn;
  background: #337ab7;
}

.btn-success {
  @extend .btn;
  background: #5cb85c;
}
```
`CSS`
```css
.btn, .btn-primary, .btn-success {
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  display: inline-block;
}

.btn-primary {
  background: #337ab7;
}

.btn-success {
  background: #5cb85c;
}
```
## 占位符选择器

占位符选择器是形如 `%foo` 的选择器，只用作被 `@extend`，不会生成具体的 CSS 规则。

`SCSS`
```sass
.footer {
  %link {
    color: #0070e9;
    text-docoration: none;
    &:hover {
      text-docoration: underline;
    }
  }
  .docs {
    @extend %link;
    font-size: 24px;
  }
  .socials {
    @extend %link;
    font-size: 28px;
  }
}
```
`CSS`
```css
.footer .docs, .footer .socials {
  color: #0070e9;
  text-docoration: none;
}
.footer .docs:hover, .footer .socials:hover {
  text-docoration: underline;
}
.footer .docs {
  font-size: 24px;
}
.footer .socials {
  font-size: 28px;
}
```
